#if !canImport(ObjectiveC)
import XCTest

extension ActivityParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActivityParserTests = [
        ("testParseActivityLog", testParseActivityLog),
        ("testParseActivityLogInURLPreservesUTF8ByteLengthStringsAndEmbeddedNullBytes", testParseActivityLogInURLPreservesUTF8ByteLengthStringsAndEmbeddedNullBytes),
        ("testParseDBGConsoleLog", testParseDBGConsoleLog),
        ("testParseDVTTextDocumentLocation", testParseDVTTextDocumentLocation),
        ("testParseIBDocumentMemberLocation", testParseIBDocumentMemberLocation),
        ("testParseIDEActivityLogAnalyzerResultMessage", testParseIDEActivityLogAnalyzerResultMessage),
        ("testParseIDEActivityLogMessage", testParseIDEActivityLogMessage),
        ("testParseIDEActivityLogSection", testParseIDEActivityLogSection),
        ("testParseIDEActivityLogSectionXcode270", testParseIDEActivityLogSectionXcode270),
        ("testParseXcode3ProjectLocation", testParseXcode3ProjectLocation),
    ]
}

extension ChromeTracerOutputTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChromeTracerOutputTests = [
        ("testTargetToTraceEvent", testTargetToTraceEvent),
    ]
}

extension IssuesReporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IssuesReporterTests = [
        ("testReport", testReport),
    ]
}

extension LexRedactorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexRedactorTests = [
        ("testMultiplePathsRedacting", testMultiplePathsRedacting),
        ("testNotInPredefinedUserDirIsNotRedacted", testNotInPredefinedUserDirIsNotRedacted),
        ("testPredefinedUserDirIsRedacted", testPredefinedUserDirIsRedacted),
        ("testRedacting", testRedacting),
        ("testRedactingComplexUsername", testRedactingComplexUsername),
        ("testRedactingFillsUserDir", testRedactingFillsUserDir),
        ("testRedactingHomePath", testRedactingHomePath),
    ]
}

extension LexerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTests = [
        ("testTokenTypeByteInitMatchesRawValueInitForEveryByte",
         testTokenTypeByteInitMatchesRawValueInitForEveryByte),
        ("testTokenizeClassName", testTokenizeClassName),
        ("testTokenizeClassNameRef", testTokenizeClassNameRef),
        ("testTokenizeDouble", testTokenizeDouble),
        ("testTokenizeError", testTokenizeError),
        ("testTokenizeInt", testTokenizeInt),
        ("testTokenizeList", testTokenizeList),
        ("testTokenizeListNil", testTokenizeListNil),
        ("testTokenizeString", testTokenizeString),
        ("testTokenizeStringRedacted", testTokenizeStringRedacted),
        ("testTokenizeStringUsesUTF8ByteLength", testTokenizeStringUsesUTF8ByteLength),
        ("testTokenizeStringWithTokenDelimiters", testTokenizeStringWithTokenDelimiters),
    ]
}

extension LogLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogLoaderTests = [
        ("testLoadFromURLPreservesEmbeddedNullBytes", testLoadFromURLPreservesEmbeddedNullBytes),
    ]
}

extension LogFinderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogFinderTests = [
        ("testGetLogManifestPathForNonExistingFile", testGetLogManifestPathForNonExistingFile),
        ("testGetLogManifestPathWithWorkspace", testGetLogManifestPathWithWorkspace),
        ("testGetLogManifestPathWithXcodeProj", testGetLogManifestPathWithXcodeProj),
        ("testGetLogsFromCustomDerivedData", testGetLogsFromCustomDerivedData),
        ("testGetProjectFolderWithHash", testGetProjectFolderWithHash),
        ("testLogsDirectoryForXcodeProject", testLogsDirectoryForXcodeProject),
    ]
}

extension LogManifestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogManifestTests = [
        ("testGetLatestLogEntry", testGetLatestLogEntry),
        ("testGetWithLogOptions", testGetWithLogOptions),
    ]
}

extension MalformedInputTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MalformedInputTests = [
        ("testTargetFromCommandWithMarkersInOrder", testTargetFromCommandWithMarkersInOrder),
        ("testTargetFromCommandWithMarkersOutOfOrder", testTargetFromCommandWithMarkersOutOfOrder),
        ("testTimeTraceFileFoundAfterNonASCIIText", testTimeTraceFileFoundAfterNonASCIIText),
        ("testTokenizeClassNameRefOutOfBounds", testTokenizeClassNameRefOutOfBounds),
        ("testTokenizeClassNameRefZero", testTokenizeClassNameRefZero),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testBuildIdentifierShouldUseMachineName", testBuildIdentifierShouldUseMachineName),
        ("testDateFormatterUsesJSONFormat", testDateFormatterUsesJSONFormat),
        ("testGetIndividualSteps", testGetIndividualSteps),
        ("testGetTargetFromCommandWithReversedMarkersDoesNotCrash",
         testGetTargetFromCommandWithReversedMarkersDoesNotCrash),
        ("testParseAppCompilationTimes", testParseAppCompilationTimes),
        ("testParseAppNoopCompilationTimes", testParseAppNoopCompilationTimes),
        ("testParseInterfaceBuilderWarning", testParseInterfaceBuilderWarning),
        ("testParseNote", testParseNote),
        ("testParseSwiftIssuesDetails", testParseSwiftIssuesDetails),
        ("testParseTargetCompilationTimes", testParseTargetCompilationTimes),
        ("testParseTargetName", testParseTargetName),
        ("testParseWarningsAndErrors", testParseWarningsAndErrors),
    ]
}

extension ReporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReporterTests = [
        ("testMakeLogReporter", testMakeLogReporter),
    ]
}

extension SwiftIssuesScanTests {
    static let __allTests__SwiftIssuesScanTests = [
        ("testAgreesOnGeneratedText", testAgreesOnGeneratedText),
        ("testAgreesOnRealisticInput", testAgreesOnRealisticInput),
        ("testCombiningMarkAfterMarkerAgreesWithFoundation", testCombiningMarkAfterMarkerAgreesWithFoundation),
        ("testEmptyLinesAndTerminators", testEmptyLinesAndTerminators),
        ("testErrorMarkerWinsRegardlessOfPosition", testErrorMarkerWinsRegardlessOfPosition),
        ("testLeadingContinuationsAreDropped", testLeadingContinuationsAreDropped),
        ("testTruncatedMarkersAtEndOfInput", testTruncatedMarkersAtEndOfInput)
    ]
}

extension SwiftCompilerParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftCompilerParserTests = [
        ("testParseSwiftFunctionTimes", testParseSwiftFunctionTimes),
        ("testParseSwiftTypeCheckTimes", testParseSwiftTypeCheckTimes),
    ]
}

extension ExactNeedleTests {
    static let __allTests__ExactNeedleTests = [
        ("testCombiningMarkAgreesWithFoundation", testCombiningMarkAgreesWithFoundation),
        ("testEmptyNeedleMatchesFoundation", testEmptyNeedleMatchesFoundation),
        ("testIsCaseSensitive", testIsCaseSensitive),
        ("testMatchesFoundationContains", testMatchesFoundationContains),
        ("testNonCombiningNonAsciiStillMatches", testNonCombiningNonAsciiStillMatches)
    ]
}

extension ByteSetTests {
    static let __allTests__ByteSetTests = [
        ("testEmptySetContainsNothing", testEmptySetContainsNothing),
        ("testFullSetContainsEverything", testFullSetContainsEverything),
        ("testMatchesSetMembershipAcrossAllBytes", testMatchesSetMembershipAcrossAllBytes)
    ]
}

extension ScannerNumberTests {
    static let __allTests__ScannerNumberTests = [
        ("testAgreesOnDecimalDigits", testAgreesOnDecimalDigits),
        ("testAgreesOnGeneratedNumbers", testAgreesOnGeneratedNumbers),
        ("testAgreesOnHexDigits", testAgreesOnHexDigits),
        ("testAgreesOnOverflow", testAgreesOnOverflow),
        ("testAgreesOnRejectedInput", testAgreesOnRejectedInput),
        ("testEmptyRangeIsRejected", testEmptyRangeIsRejected)
    ]
}

extension ClangWarningFlagsTests {
    static let __allTests__ClangWarningFlagsTests = [
        ("testAgreesAcrossEmbeddedNulBytes", testAgreesAcrossEmbeddedNulBytes),
        ("testAgreesOnGeneratedText", testAgreesOnGeneratedText),
        ("testAgreesOnNonAsciiFlags", testAgreesOnNonAsciiFlags),
        ("testMatchesRegexOnPatternEdgeCases", testMatchesRegexOnPatternEdgeCases),
        ("testMatchesRegexOnRealisticDiagnostics", testMatchesRegexOnRealisticDiagnostics),
        ("testScannerAgreesOnGeneratedText", testScannerAgreesOnGeneratedText)
    ]
}

extension ISO8601DateStringTests {
    static let __allTests__ISO8601DateStringTests = [
        ("testFractionCarriesIntoSeconds", testFractionCarriesIntoSeconds),
        ("testFractionIsMillisecondsZeroExtended", testFractionIsMillisecondsZeroExtended),
        ("testHalfMillisecondTieDivergesFromDateFormatter", testHalfMillisecondTieDivergesFromDateFormatter),
        ("testKnownTimestamp", testKnownTimestamp),
        ("testLeapDay", testLeapDay),
        ("testMatchesDateFormatterAcrossCentury", testMatchesDateFormatterAcrossCentury),
        ("testNegativeInterval", testNegativeInterval),
        ("testReferenceEpoch", testReferenceEpoch),
        ("testTypicalFourDecimalTimestampAgrees", testTypicalFourDecimalTimestampAgrees)
    ]
}

extension CaseFoldingTests {
    static let __allTests__CaseFoldingTests = [
        ("testCombiningMarkAgreesWithFoundation", testCombiningMarkAgreesWithFoundation),
        ("testContainsAgreesWithFoundation", testContainsAgreesWithFoundation),
        ("testDifferentialSweep", testDifferentialSweep),
        ("testEmbeddedNulBytesAgreeWithFoundation", testEmbeddedNulBytesAgreeWithFoundation),
        ("testEmptyPatternKeepsFoundationsAsymmetry", testEmptyPatternKeepsFoundationsAsymmetry),
        ("testNonCombiningNonAsciiStillMatches", testNonCombiningNonAsciiStillMatches),
        ("testPatternLongerThanInput", testPatternLongerThanInput),
        ("testPrefixAgreesWithFoundation", testPrefixAgreesWithFoundation),
        ("testScalarsThatLowercaseIntoAsciiAgreeWithFoundation",
         testScalarsThatLowercaseIntoAsciiAgreeWithFoundation),
        ("testSuffixAgreesWithFoundation", testSuffixAgreesWithFoundation)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ActivityParserTests.__allTests__ActivityParserTests),
        testCase(ByteSetTests.__allTests__ByteSetTests),
        testCase(ClangWarningFlagsTests.__allTests__ClangWarningFlagsTests),
        testCase(ScannerNumberTests.__allTests__ScannerNumberTests),
        testCase(CaseFoldingTests.__allTests__CaseFoldingTests),
        testCase(ExactNeedleTests.__allTests__ExactNeedleTests),
        testCase(ISO8601DateStringTests.__allTests__ISO8601DateStringTests),
        testCase(ChromeTracerOutputTests.__allTests__ChromeTracerOutputTests),
        testCase(IssuesReporterTests.__allTests__IssuesReporterTests),
        testCase(LexRedactorTests.__allTests__LexRedactorTests),
        testCase(LexerTests.__allTests__LexerTests),
        testCase(LogLoaderTests.__allTests__LogLoaderTests),
        testCase(LogFinderTests.__allTests__LogFinderTests),
        testCase(LogManifestTests.__allTests__LogManifestTests),
        testCase(MalformedInputTests.__allTests__MalformedInputTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(ReporterTests.__allTests__ReporterTests),
        testCase(SwiftCompilerParserTests.__allTests__SwiftCompilerParserTests),
        testCase(SwiftIssuesScanTests.__allTests__SwiftIssuesScanTests),
    ]
}
#endif
