// Copyright (c) 2019 Spotify AB.
//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import Foundation

/// Parses Swift Function times generated by `swiftc`
/// if you pass the flags `-Xfrontend -debug-time-function-bodies`
class SwiftCompilerFunctionTimeOptionParser: SwiftCompilerTimeOptionParser {

    private static let compilerFlag = "-debug-time-function-bodies"
    private static let compilerFlagNeedle = ExactNeedle(compilerFlag)

    func hasCompilerFlag(commandDesc: String) -> Bool {
        Self.compilerFlagNeedle.matches(commandDesc)
    }

    func file(of option: SwiftFunctionTime) -> String {
        option.file
    }

    func parse(from commands: [String: Int]) -> [String: [SwiftFunctionTime]] {
        var functionsPerFile: [String: [SwiftFunctionTime]] = [:]
        for (command, occurrences) in commands {
            guard let functions = parse(command: command, occurrences: occurrences) else {
                continue
            }
            merge(functions, into: &functionsPerFile)
        }
        return functionsPerFile
    }

    func parse(command: String, occurrences: Int) -> [SwiftFunctionTime]? {
        return command.split(separator: "\r", omittingEmptySubsequences: false).compactMap { commandLine in
            parse(fields: commandLine.split(separator: "\t", omittingEmptySubsequences: false),
                  occurrences: occurrences)
        }
    }

    func parse(utf8Fields: [String.UTF8View.SubSequence],
               occurrences: Int,
               fileURLs: FileURLCache) -> SwiftFunctionTime? {
        // 0.14ms   /users/mnf/project/SomeFile.swift:10:12   someMethod(param:)
        guard utf8Fields.count == 3 else {
            return nil
        }
        guard let (file, line, column) = parseNameAndLocation(fromUTF8: utf8Fields[1], fileURLs: fileURLs) else {
            return nil
        }
        // swiftlint:disable:next optional_data_string_conversion
        let signature = String(decoding: utf8Fields[2], as: UTF8.self)
        return SwiftFunctionTime(file: file,
                                 durationMS: parseCompileDuration(fromUTF8: utf8Fields[0]),
                                 startingLine: line,
                                 startingColumn: column,
                                 signature: signature,
                                 occurrences: occurrences)
    }

    func parse(fields: [Substring], occurrences: Int) -> SwiftFunctionTime? {
        // 0.14ms   /users/mnf/project/SomeFile.swift:10:12   someMethod(param:)
        guard fields.count == 3 else {
            return nil
        }

        // 0.14ms
        let duration = parseCompileDuration(fields[0])

        // /users/mnf/project/SomeFile.swift:10:12
        guard let (file, line, column) = parseNameAndLocation(from: fields[1]) else {
            return nil
        }

        // someMethod(param:)
        return SwiftFunctionTime(file: file,
                                 durationMS: duration,
                                 startingLine: line,
                                 startingColumn: column,
                                 signature: String(fields[2]),
                                 occurrences: occurrences)
    }
}
