// Copyright (c) 2019 Spotify AB.
//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import Foundation

/// Parses Swift Function times generated by `swiftc`
/// if you pass the flags `-Xfrontend -debug-time-expression-type-checking`
class SwiftCompilerTypeCheckOptionParser: SwiftCompilerTimeOptionParser {

    private static let compilerFlag = "-debug-time-expression-type-checking"
    private static let compilerFlagNeedle = ExactNeedle(compilerFlag)

    func hasCompilerFlag(commandDesc: String) -> Bool {
        Self.compilerFlagNeedle.matches(commandDesc)
    }

    func file(of option: SwiftTypeCheck) -> String {
        option.file
    }

    func parse(from commands: [String: Int]) -> [String: [SwiftTypeCheck]] {
        var typeChecksPerFile: [String: [SwiftTypeCheck]] = [:]
        for (command, occurrences) in commands {
            guard let typeChecks = parse(command: command, occurrences: occurrences) else {
                continue
            }
            merge(typeChecks, into: &typeChecksPerFile)
        }
        return typeChecksPerFile
    }

    func parse(command: String, occurrences: Int) -> [SwiftTypeCheck]? {
        return command.split(separator: "\r", omittingEmptySubsequences: false).compactMap { commandLine in
            parse(fields: commandLine.split(separator: "\t", omittingEmptySubsequences: false),
                  occurrences: occurrences)
        }
    }

    func parse(utf8Fields: [String.UTF8View.SubSequence],
               occurrences: Int,
               fileURLs: FileURLCache) -> SwiftTypeCheck? {
        // 0.14ms   /users/mnf/project/SomeFile.swift:10:12
        guard utf8Fields.count == 2 else {
            return nil
        }
        guard let (file, line, column) = parseNameAndLocation(fromUTF8: utf8Fields[1], fileURLs: fileURLs) else {
            return nil
        }
        return SwiftTypeCheck(file: file,
                              durationMS: parseCompileDuration(fromUTF8: utf8Fields[0]),
                              startingLine: line,
                              startingColumn: column,
                              occurrences: occurrences)
    }

    func parse(fields: [Substring], occurrences: Int) -> SwiftTypeCheck? {
        // 0.14ms   /users/mnf/project/SomeFile.swift:10:12
        guard fields.count == 2 else {
            return nil
        }

        // 0.14ms
        let duration = parseCompileDuration(fields[0])

        // /users/mnf/project/SomeFile.swift:10:12
        guard let (file, line, column) = parseNameAndLocation(from: fields[1]) else {
            return nil
        }

        return SwiftTypeCheck(file: file,
                              durationMS: duration,
                              startingLine: line,
                              startingColumn: column,
                              occurrences: occurrences)
    }

}
